apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: item-api
  name: item-api
  namespace: item-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: item-api
    spec:
      containers:
      - image: docker.io/onsd/item-api:0.13
        name: item-api
        env:
        - name: PORT
          value: "8080"
        - name: DEBUG
          value: "true"
        - name: DATABASE_URL
          value: "postgres://dbuser:password@cockroachdb-public.cockroachdb:26257/defaultdb?sslmode=require"
        - name: AZURE_STORAGE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: item-api-secret
              key: AZURE_STORAGE_ACCOUNT_NAME
        - name: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: item-api-secret
              key: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
