apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: item-api-ingress
  namespace: item-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: api.inol.cf
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: item-api
            port:
              number: 80