apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: item-api
  name: item-api
  namespace: item-api
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: item-api
  type: ClusterIP