apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ws-server
  name: ws-server
  namespace: ws-server
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ws-server
  type: ClusterIP