apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onsd-item-api-ingress
  namespace: onsd-item-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: api.inol.cf
    http:
      paths:
      - path: /onsd/(.*)
        pathType: Prefix
        backend:
          service:
            name: onsd-item-api
            port:
              number: 80
