# .github/workflows/build.yml

on: pull_request

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: kankodori.azurecr.io
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: ./backend/item-api
          push: true
          tags: docker.io/onsd/test-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

